auth_user.find (0.00) {'username': 'sys'}
django_session.save (0.00) {'_id': u'arw5uq5pg1ydiyjeo9k6cs2pd4rsmitt', 'expire_date': datetime.datetime(2018, 5, 19, 3, 14, 43, 878000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /favicon.ico
django_session.find (0.00) {'_id': 'arw5uq5pg1ydiyjeo9k6cs2pd4rsmitt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 14, 45, 340000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': u'jl66r1wp7p8u614szofmcedphv7l9ofc', 'expire_date': datetime.datetime(2018, 5, 19, 3, 14, 45, 525000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': 'arw5uq5pg1ydiyjeo9k6cs2pd4rsmitt'}
django_session.remove (0.00) {'_id': {'$in': [u'arw5uq5pg1ydiyjeo9k6cs2pd4rsmitt']}}
auth_user.save (0.00) {'username': u'sys', 'first_name': u'', 'last_name': u'', '_id': ObjectId('5ae5cb53cddcb0354c11cf6a'), 'is_active': True, 'email': u'', 'is_superuser': True, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 5, 3, 14, 45, 531000, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$RM3mR6ar66t8$SRS3qPBkBP7FldCNOuunX0f1RK/YppeImlg2lVhOJZo=', 'date_joined': datetime.datetime(2018, 4, 29, 13, 40, 35, 764000, tzinfo=<UTC>)}
django_session.save (0.00) {'_id': u'jl66r1wp7p8u614szofmcedphv7l9ofc', 'expire_date': datetime.datetime(2018, 5, 19, 3, 14, 45, 580000, tzinfo=<UTC>), 'session_data': u'MmU5YzEwYjExYTI3YTY2YmIwMGM0YmYwZWUwYmFkNmZjYzQyMzQ1OTp7Il9hdXRoX3VzZXJfYmFja2VuZCI6InBlcm1pc3Npb25fYmFja2VuZF9ub25yZWwuYmFja2VuZHMuTm9ucmVsUGVybWlzc2lvbkJhY2tlbmQiLCJfYXV0aF91c2VyX2lkIjoiNWFlNWNiNTNjZGRjYjAzNTRjMTFjZjZhIiwibGFuZ3VhZ2UiOiJlbiJ9'}
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': 'jl66r1wp7p8u614szofmcedphv7l9ofc', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 14, 45, 607000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages\quicky\view.py", line 76, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'models'
django_session.find (0.00) {'_id': 'jl66r1wp7p8u614szofmcedphv7l9ofc', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 14, 51, 223000, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': 'jl66r1wp7p8u614szofmcedphv7l9ofc', 'expire_date': datetime.datetime(2018, 5, 19, 3, 14, 51, 257000, tzinfo=<UTC>), 'session_data': u'OTY1MDE0OGZmZDhiNDE0NjM4MDg4ZDE5ZDQzOGI2MTk2OGY2NWNjZDp7Imxhbmd1YWdlIjoiZW4iLCJfYXV0aF91c2VyX2lkIjoiNWFlNWNiNTNjZGRjYjAzNTRjMTFjZjZhIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoicGVybWlzc2lvbl9iYWNrZW5kX25vbnJlbC5iYWNrZW5kcy5Ob25yZWxQZXJtaXNzaW9uQmFja2VuZCJ9'}
auth_user.find (0.01) {'username': 'sys'}
auth_user.find (0.01) {'username': 'sys'}
django_session.save (0.00) {'_id': u'clla3ar31wwebsalcwwyjloouuj3ewr0', 'expire_date': datetime.datetime(2018, 5, 19, 3, 16, 26, 465000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': 'clla3ar31wwebsalcwwyjloouuj3ewr0', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 16, 35, 515000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': u'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': datetime.datetime(2018, 5, 19, 3, 16, 35, 605000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': 'clla3ar31wwebsalcwwyjloouuj3ewr0'}
django_session.remove (0.00) {'_id': {'$in': [u'clla3ar31wwebsalcwwyjloouuj3ewr0']}}
auth_user.save (0.00) {'username': u'sys', 'first_name': u'', 'last_name': u'', '_id': ObjectId('5ae5cb53cddcb0354c11cf6a'), 'is_active': True, 'email': u'', 'is_superuser': True, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 5, 3, 16, 35, 609000, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$RM3mR6ar66t8$SRS3qPBkBP7FldCNOuunX0f1RK/YppeImlg2lVhOJZo=', 'date_joined': datetime.datetime(2018, 4, 29, 13, 40, 35, 764000, tzinfo=<UTC>)}
django_session.save (0.00) {'_id': u'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': datetime.datetime(2018, 5, 19, 3, 16, 35, 612000, tzinfo=<UTC>), 'session_data': u'MmU5YzEwYjExYTI3YTY2YmIwMGM0YmYwZWUwYmFkNmZjYzQyMzQ1OTp7Il9hdXRoX3VzZXJfYmFja2VuZCI6InBlcm1pc3Npb25fYmFja2VuZF9ub25yZWwuYmFja2VuZHMuTm9ucmVsUGVybWlzc2lvbkJhY2tlbmQiLCJfYXV0aF91c2VyX2lkIjoiNWFlNWNiNTNjZGRjYjAzNTRjMTFjZjZhIiwibGFuZ3VhZ2UiOiJlbiJ9'}
auth_user.find (0.01) {'username': 'sys'}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 16, 38, 847000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages\quicky\view.py", line 76, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'models'
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 17, 0, 980000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages\quicky\view.py", line 76, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'models'
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 17, 14, 581000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages\quicky\view.py", line 76, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'models'
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 17, 30, 688000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 18, 19, 549000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 18, 36, 531000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Not Found: /hrm/static/js/jquery-3.3.1.min.js
Not Found: /hrm/static/bs/css/bootstrap-theme.min.css
Not Found: /hrm/static/bs/js/bootstrap.min.js
Not Found: /hrm/static/bs/css/bootstrap.min.css
Not Found: /hrm/static/js/ngDirectives.js
Not Found: /hrm/static/js/angular.min.js
Not Found: /hrm/static/js/ws.js
Not Found: /hrm/static/css/site.css
Not Found: /hrm/static/js/promise-6.1.0.js
Not Found: /hrm/static/bs/css/bootstrap-theme.min.css
Not Found: /hrm/static/bs/css/bootstrap.min.css
Not Found: /hrm/static/css/site.css
Not Found: /hrm/static/js/jquery-3.3.1.min.js
Not Found: /hrm/static/js/jquery-3.3.1.min.js
Not Found: /hrm/static/js/jquery-3.3.1.min.js
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 10, 622000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 12, 311000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 33, 620000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages/django\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\packages/django\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018\apps\hrm\views.py", line 69, in api
    view_privileges=quicky.get_settings().AUTHORIZATION_ENGINE.get_view_of_user(
AttributeError: 'module' object has no attribute 'get_settings'
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 33, 782000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 39, 989000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\packages/django\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\packages/django\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\packages/django\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018\apps\hrm\views.py", line 69, in api
    view_privileges=quicky.get_settings().AUTHORIZATION_ENGINE.get_view_of_user(
AttributeError: 'module' object has no attribute 'get_settings'
django_session.find (0.00) {'_id': 'r9r25ef0fmbuki62vcsi4flg3b19iwvg', 'expire_date': {'$gt': datetime.datetime(2018, 5, 5, 3, 21, 40, 100000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
