Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 29, in exec_request
    login_url=app.get_login_url()
  File "/home/hcsadmin/argo/packages/quicky/app_info.py", line 79, in get_login_url
    if hasattr(self.mdl.settings,"login_url"):
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 29, in exec_request
    login_url=app.get_login_url()
  File "/home/hcsadmin/argo/packages/quicky/app_info.py", line 79, in get_login_url
    if hasattr(self.mdl.settings,"login_url"):
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 29, in exec_request
    login_url=app.get_login_url()
  File "/home/hcsadmin/argo/packages/quicky/app_info.py", line 79, in get_login_url
    if hasattr(self.mdl.settings,"login_url"):
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 29, in exec_request
    login_url=app.get_login_url()
  File "/home/hcsadmin/argo/packages/quicky/app_info.py", line 79, in get_login_url
    if hasattr(self.mdl.settings,"login_url"):
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 29, in exec_request
    is_public = False
  File "/home/hcsadmin/argo/packages/quicky/app_info.py", line 79, in get_login_url
    if hasattr(self.mdl.settings,"login_url"):
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 68, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 69, in exec_request
    raise (ex)
AttributeError: 'module' object has no attribute 'settings'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 69, in exec_request
    raise (ex)
Exception: 'settings.py' was not found in 'argo' at ''
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 69, in exec_request
    logger.debug(ex)
Exception: 'settings.py' was not found in 'argo' at ''
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 70, in exec_request
    raise (ex)
Exception: 'settings.py' was not found in 'argo' at '/home/hcsadmin/argo/apps/app_main'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 70, in exec_request
    raise (ex)
Exception: 'settings.py' was not found in 'argo' at '/home/hcsadmin/argo/apps/app_main'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 70, in exec_request
    raise (ex)
Exception: 'settings.py' was not found in 'argo' at '/home/hcsadmin/argo/apps/app_main' or look like you forgot to place 'import settings' in '/home/hcsadmin/argo/apps/app_main/__init__.py'
auth_user.find (0.00) {'username': 'sys'}
auth_user.save (0.01) {'username': 'sys', 'first_name': u'', 'last_name': u'', 'is_active': True, '_id': ObjectId('5ae927ee927e004485ecfdbd'), 'is_superuser': False, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 2, 2, 52, 30, 396879, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$W6BlKFAVi3wa$mhnhlveWW8phbnP3dDiBLKagO4W2z0LbiKIMcehChKU=', 'email': u'', 'date_joined': datetime.datetime(2018, 5, 2, 2, 52, 30, 396879, tzinfo=<UTC>)}
auth_user.save (0.00) {'username': 'sys', 'first_name': u'', 'last_name': u'', '_id': ObjectId('5ae927ee927e004485ecfdbd'), 'is_active': True, 'email': u'', 'is_superuser': False, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 2, 2, 52, 30, 396879, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$W6BlKFAVi3wa$mhnhlveWW8phbnP3dDiBLKagO4W2z0LbiKIMcehChKU=', 'date_joined': datetime.datetime(2018, 5, 2, 2, 52, 30, 396879, tzinfo=<UTC>)}
Not Found: /login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /login
Not Found: /login
Not Found: /login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /login
Not Found: /login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /login
auth_user.find (0.01) {'username': 'sys'}
Not Found: /login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /127.0.0.1:8000/login
auth_user.find (0.00) {'username': 'sys'}
Not Found: /127.0.0.1:8000/login
auth_user.find (0.00) {'username': 'sys'}
django_session.save (0.01) {'_id': u'60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 0, 59, 442617, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 1, 14, 863810, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 1, 14, 891073, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 1, 43, 344080, tzinfo=<UTC>)}}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 1, 43, 375484, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 1, 43, 430779, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /jjjjjj
Not Found: /argo/static/js/jquery-3.3.1.min.js
Internal Server Error: /argo/static/js/jquery-3.3.1.min.js
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/hcsadmin/argo/packages/django/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 600, in is_valid_path
    resolve(path, urlconf)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 480, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
AttributeError: 'list' object has no attribute 'resolve'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
AttributeError: 'list' object has no attribute 'resolve'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
AttributeError: 'list' object has no attribute 'resolve'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 339, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/hcsadmin/argo/packages/django/django/core/urlresolvers.py", line 369, in url_patterns
    raise ImproperlyConfigured("The included urlconf %s doesn't have any patterns in it" % self.urlconf_name)
ImproperlyConfigured: The included urlconf None doesn't have any patterns in it
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 51, 22, 454061, tzinfo=<UTC>)}}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 51, 26, 574426, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 51, 26, 627178, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 54, 29, 72, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 54, 29, 76982, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/
Not Found: /admin/
Not Found: /admin/
Not Found: /admin/
Internal Server Error: /hrm
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Not Found: /admin/
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 56, 7, 952063, tzinfo=<UTC>)}}
Not Found: /admin/login
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 4, 65045, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 4, 130693, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 9, 566711, tzinfo=<UTC>)}}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 9, 588855, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 9, 628264, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/css/site.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 15, 549776, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 15, 674822, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 19, 181299, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 19, 292672, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 20, 792276, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 20, 893261, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.01) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 21, 514518, tzinfo=<UTC>)}}
auth_user.find (0.01) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 21, 775486, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 25, 831947, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 26, 6658, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 57, 34, 161225, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'root'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 57, 34, 262153, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/toast/bootoast.min.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 3, 59, 11, 444170, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 3, 59, 11, 535724, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 2, 4, 582795, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'root'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 4, 2, 4, 729360, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/js/ws.js
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/argo/__init__.py", line 41, in exec_request
    _on_begin_request=getattr(app,"on_begin_request")
AttributeError: 'NoneType' object has no attribute 'on_begin_request'
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 4, 43, 552026, tzinfo=<UTC>)}}
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 71, in exec_request
    raise (ex)
TypeError: coercing to Unicode: need string or buffer, NoneType found
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 5, 19, 423645, tzinfo=<UTC>)}}
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 71, in exec_request
    raise (ex)
TypeError: coercing to Unicode: need string or buffer, NoneType found
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 6, 47, 686680, tzinfo=<UTC>)}}
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 71, in exec_request
    raise (ex)
TypeError: coercing to Unicode: need string or buffer, NoneType found
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 7, 24, 957094, tzinfo=<UTC>)}}
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 71, in exec_request
    except Exception as ex:
TypeError: coercing to Unicode: need string or buffer, NoneType found
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 10, 11, 48066, tzinfo=<UTC>)}}
Internal Server Error: /hrm/
Traceback (most recent call last):
  File "/home/hcsadmin/argo/packages/django/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hcsadmin/argo/packages/quicky/view.py", line 73, in exec_request
    raise (ex)
Exception: it look like you forgot set 'login_url' in apps/hrm.settings.py
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 10, 49, 159288, tzinfo=<UTC>)}}
Not Found: /hrm/~/login
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 11, 56, 23873, tzinfo=<UTC>)}}
Not Found: /hrm/admin/login
Not Found: /hrm/~/login
Not Found: /hrm/~/login
Not Found: /hrm/~/login
Not Found: /hrm/~/login
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 14, 11, 948945, tzinfo=<UTC>)}}
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 14, 13, 45609, tzinfo=<UTC>)}}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 4, 14, 13, 114483, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/js/ws.js
django_session.find (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': {'$gt': datetime.datetime(2018, 5, 2, 4, 14, 29, 718245, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': '60vyrel3203a7ix25h0zlw7v9aylbrmj', 'expire_date': datetime.datetime(2018, 5, 16, 4, 14, 29, 823967, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/toast/bootoast.min.js
Not Found: /admin/static/css/site.css
Not Found: /admin/static/js/ws.js
Not Found: /admin/static/toast/bootoast.min.css
Not Found: /admin/static/css/site.css
Not Found: /admin/static/js/ws.js
